---
name: CI

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 5"

defaults:
  run:
    working-directory: 'nephelaiio.plugins'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: check out the codebase
        uses: actions/checkout@v2
        with:
          path: 'nephelaiio.plugins'

      - name: set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install test dependencies
        run: pip3 install poetry

      - name: install poetry
        run: poetry install

      - name: test code
        run: make
